// <auto-generated />
using System;
using DataStillCase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataStillCase.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .UseCollation("Turkish_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataStillCase.Entity.Models.Tables.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("CITIES", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adıyaman"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Afyonkarahisar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ağrı"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amasya"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Artvin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Aydın"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Balıkesir"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bilecik"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bingöl"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bitlis"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bolu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Burdur"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bursa"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Çanakkale"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Çankırı"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Çorum"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Denizli"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Diyarbakır"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Edirne"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Elazığ"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Erzincan"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Erzurum"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Eskişehir"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Gaziantep"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Giresun"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Gümüşhane"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hakkari"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hatay"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Isparta"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Mersin"
                        },
                        new
                        {
                            Id = 34,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 35,
                            Name = "İzmir"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Kars"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Kastamonu"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Kayseri"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Kırklareli"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Kırşehir"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Kocaeli"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Konya"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Kütahya"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Malatya"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Manisa"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Kahramanmaraş"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Mardin"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Muğla"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Muş"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Nevşehir"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Niğde"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ordu"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Rize"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Sakarya"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Samsun"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Siirt"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Sinop"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Sivas"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Tekirdağ"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Tokat"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Trabzon"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Tunceli"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Şanlıurfa"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Uşak"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Van"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Yozgat"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Zonguldak"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Aksaray"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Bayburt"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Karaman"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Kırıkkale"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Batman"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Şırnak"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Bartın"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ardahan"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iğdır"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Yalova"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Karabük"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Kilis"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Osmaniye"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Düzce"
                        });
                });

            modelBuilder.Entity("DataStillCase.Entity.Models.Tables.Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<string>("Editor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Editor");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Latitude");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Longitude");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("INFORMATIONS", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Editor = "Sabancı Merkez Camii, Varda(Alman) Köprüsü,Taş Köprü,Büyük Saat, Yılankale, Ulu Camii ve Külliyesi",
                            Latitude = "35-E-18",
                            Longitude = "37-N-01"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Editor = "Nemrut Dağı, Cendere Köprüsü,Pirin Ören Yeri Su Gözü,Gölbaşı Gölleri Tabiat Parkı ",
                            Latitude = "38-E-17",
                            Longitude = "37-N-46"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Editor = "Karahisar Kalesi,Ulu Camii,Frig Vadisi Tabiat Parkı,Başkomutan Tarihi Milli Parkı,Kocatepe  ",
                            Latitude = "30-E-33",
                            Longitude = "38-N-45"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Editor = "Ağrı Dağı,İshak Paşa Sarayı,Urartu Kalesi, Diyadin KAplıcaları,Kudret Köprüsü  ",
                            Latitude = "43-E-03",
                            Longitude = "39-N-44"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Editor = " II.Beyazıt Camii ve Külliyesi, Amasya Arkeoloji Müzesi, Amasya Kalesi,Boraboy Gölü Tabiat Parkı, Kral Kaya Mezarları ",
                            Latitude = "35-E-50",
                            Longitude = "40-N-40"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Editor = "Anıtkabir, Anadolu Medeniyetleri Müzesi,  I.TBMM Kurtuluş Savaşı Müzesi,Ankara Kalesi, II. TBMM Cumhuriyet Müzesi,Rahmi M. Koç Müzesi ",
                            Latitude = "32-E-52",
                            Longitude = "39-N-56"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Editor = "Kaleiçi,Apollon Tapınağı,Düden Şelalaesi, Kleopatra Plajı,Side Anfi Tiyatrosu ",
                            Latitude = "30-E-42 ",
                            Longitude = "36-N-54"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            Editor = "Mençuna Şelalesi, Karagöl, Çifte Köprü, Borçka Tabiat Parkı, İşhan Kilisesi ",
                            Latitude = "41-E-49 ",
                            Longitude = "41-N-11"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 9,
                            Editor = " Dilek Yarımadası Milli Parkı, Aphrodisias Antik Kenti, Altınkum Plajı, Küçükada Kalesi, Priene Antik Kenti",
                            Latitude = "27-E-51 ",
                            Longitude = "37-N-51"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 10,
                            Editor = "Kaz Dağları, Şeytan Sofrası, Taksiyarhis Kilisesi, Kazdağları Milli Parkı, Şahinderesi Kanyonu ",
                            Latitude = "27-E-52",
                            Longitude = "39-N-39"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            Editor = "Ertuğrul Gazi Türbesi, Şeyh Edebali Türbesi, Dursun Fakih Türbesi,Harmankaya Kanyonu Tabiat Parkı, Küçükelmalı Tabiat Parkı ",
                            Latitude = "29-E-59 ",
                            Longitude = "40-N-09"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 12,
                            Editor = "Yüzen Ada, 33 Şehit Anıtı, Buban Bacaları ",
                            Latitude = "40-E-29",
                            Longitude = "38-N-53"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 13,
                            Editor = " ",
                            Latitude = "42-E-06",
                            Longitude = "38-N-22"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 14,
                            Editor = "Gölcük Gölü, Abant Gölü, Yedigöller Milli Parkı, Göynük ZaferKulesi, Kartalkaya Kış Turizm Merkezi ",
                            Latitude = " 31-E-37",
                            Longitude = "40-N-44"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 15,
                            Editor = "Sagalassos Arkeolojik Buluntular, Salda Gölü,Arkeoloji Müzesi,Kibyra Antik Kenti,İnsuyu Mağarası ",
                            Latitude = "30-E-17",
                            Longitude = "37-N-43"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 16,
                            Editor = "Ulu Camii, Koza Hanı, Osman Gazi ve Orhan Gazi Türbeleri, Bursa Teleferik, Cumalıkızık",
                            Latitude = "29-E-04",
                            Longitude = "40-N-11"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 17,
                            Editor = " Truva Antik Kenti, Çanakkale Deniz Müzesi, Troya Müzesi,Conk Bayırı Mehmetçik Park Anıtı Kemalyeri Yazıtı, Kabatepe Kumsalı",
                            Latitude = "26-E-24 ",
                            Longitude = "40 N 09"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 18,
                            Editor = "Hazım Dağlı Tabiat Parkı, Tuz Mağarası, Çankırı Müzesi,Kırkpınar Yaylası, Bayramören Köprüsü  ",
                            Latitude = "33-E-37 ",
                            Longitude = "40-N-36"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 19,
                            Editor = " Hattuşaş, Yazılıkaya,Alacahöyük Müzesi,Aslanlı Kapı, İncesu Kanyonu ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 20,
                            CityId = 20,
                            Editor = "Pamukkale Travertenleri,Gemiş Yamaç Paraşütü, Kaklık Mağarası,Kleopatra Havuzları  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 21,
                            CityId = 21,
                            Editor = "Ulu Camii, Diyarbakır Surları,Hasankeyf Eski Köprüsü,Surp Giragos Kilisesi,Hasan Paşa Hanı  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 22,
                            CityId = 22,
                            Editor = "Selimiye Camii, Bayezid Külliyesi ve Şifahane,KAraağaç, MEriç Köprüsü, Edirne büyük Sinagogu  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 23,
                            CityId = 23,
                            Editor = "Harput Kalesi, Keban Barajı, Şefik Gül Kültür Evi, Harput Ulu Camii,Kömürhan Köprüsü  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 24,
                            CityId = 24,
                            Editor = "Girlevik Şelalesi, KEmaliye Karanlık Kanyon, Ekşisu Mesire Alanı, Atatürk Portresi, Erzincan Saat Kulesi  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 25,
                            CityId = 25,
                            Editor = " Yakutiye Medresesi, Çifte Minareli Medrese, Tortum Şelalesi,Palandöken Dağı,Erzurum Kongre ve Milli Mücadele Müzesi ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 26,
                            CityId = 26,
                            Editor = "Sazaova Parkı, Yılmaz Büyükerşen Balmumu Heykeller Müzesi, Eskişehir Bilim Sanat ve Kültür Parkı,Çağdaş Cam Sanatları MErkezi, Odunpazarı Evleri  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 27,
                            CityId = 27,
                            Editor = "Zeugma Mozaik Müzesi, Rumkale, Gaziantep Kalesi, Gaziantep Hayvanat Bahçesi, Gaziantep Oyun ve Oyuncak Müzesi  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 28,
                            CityId = 28,
                            Editor = "Giresun Kalesi, Kulakkaya Yaylası, Kuzalan Şelalesi,Kümbet Yaylası,Sis Dağı  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 29,
                            CityId = 29,
                            Editor = "Tomara Şelalesi Tabiat Parkı, Karaca Cave, Limni Gölü Tabiat Parkı,Taşköprü Yaylası,İkizevler Kent Müzesi  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 30,
                            CityId = 30,
                            Editor = " Beyaz Şelale, Cilo Buzulları, Sat Buzul Gölleri,Tarihi Taş Evler, Meydan MEdresesi ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 31,
                            CityId = 31,
                            Editor = " Antakya Arkeoloji Müzesi,Eski Antakya,Habib-i Neccar Camii,Titus Kaya Tüneli, St. Pierre Kilisesi ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 32,
                            CityId = 32,
                            Editor = "Eğirdir Gölü, Kuyucak Köyü, Süleyman Demirel Demokrasi ve Kalkınma Müzesi,Zindan Mağarası, Kızıldağ Milli Parkı  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 33,
                            CityId = 33,
                            Editor = "Aynalıgöl Mağarası, Uzuncaburç Olba Antik Kenti, Mut Yerköprü Şelalesi,Kızkalesi, Alahan Manastırı   ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 34,
                            CityId = 34,
                            Editor = "Ayasofya Camii, Galata Kulesi, Gülhane Parkı, Dolmabahçe Sarayı, Yerebatan Sarnıcı    ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 35,
                            CityId = 35,
                            Editor = " Kordon Boyu, Kemeraltı Çarşısı,Saat Kulesi,Tarihi Asansör,İzmir Doğal Yaşam Parkı  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 36,
                            CityId = 36,
                            Editor = " Ani Antik Kenti,Havariler Müzesi, Kars Kalesi,Ani Katedrali, Kafkas Cephesi Harp Tarihi Müzesi  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 37,
                            CityId = 37,
                            Editor = "Hz. Pir Şeyh Şaban-i Veli Külliyesi, Ilıca Şelalesi, Nasrullah Camii,Kastamonu Kalesi,Valla Kanyonu Seyir Terası   ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 38,
                            CityId = 38,
                            Editor = " Erciyes Dağı, Hunat Hatun Külliyesi,Soğanlı Vadisi,Kayseri Lisesi Milli Mücadele Müzesi, Mimar Sinan Evi ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 39,
                            CityId = 39,
                            Editor = "İğneada Longoz Ormanları Milli Parkı, Dupnisa Mağarası,Atatürk Evi,Kıyıköy Çiftliği, Sokullu Mehmet Paşa Camii   ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 40,
                            CityId = 40,
                            Editor = "Japon Bahçesi, Cacabey MEdresesi, Kaman KAlehöyük Arkeoloji Müzesi,Ahi Evran Külliyesi ve Camii,Neşet Etraş Kültür Merkezi   ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 41,
                            CityId = 41,
                            Editor = "Ormanya,Gayret Gemi Müzesi,İzmit Saat Kulesi,Kocaeli Bilim Müzesi, Pembe KayalarBallıkayalar Kanyonu   ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 42,
                            CityId = 42,
                            Editor = "Mevlana Müzesi, Konya Tropikal Kelebek Bahçesi, Sille Köyü, Aziziye Camii, Konya Bilim Merkezi  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 43,
                            CityId = 43,
                            Editor = " Aizanoi Antik Kenti, Dumlupınar Şehitliği,Kütahya Kalesi, Macar Evi Müzesi,Çini Müzesi  ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 44,
                            CityId = 44,
                            Editor = "  Şire Pazarı,Silahtar Mustafa Paşa Kervansarayı, Levent Vadisi, Malatya Beşkonaklar Etnografya Müzesi, Aslantepe Ören Yeri ",
                            Latitude = "",
                            Longitude = ""
                        },
                        new
                        {
                            Id = 45,
                            CityId = 45,
                            Editor = "Spil Dağı, Aigai Antik Kenti, Manisa Müzesi,Süreyya Tabiat Parkı, Kula Peribacaları",
                            Latitude = "",
                            Longitude = ""
                        });
                });

            modelBuilder.Entity("DataStillCase.Entity.Models.Tables.VisitorHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("VisitorCount")
                        .HasColumnType("int")
                        .HasColumnName("VisitorCount");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("VISITORHISTORIES", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 100
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 200
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 90
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 300
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 200
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 150
                        },
                        new
                        {
                            Id = 7,
                            CityId = 2,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 80
                        },
                        new
                        {
                            Id = 8,
                            CityId = 2,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 350
                        },
                        new
                        {
                            Id = 9,
                            CityId = 3,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 400
                        },
                        new
                        {
                            Id = 10,
                            CityId = 3,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 200
                        },
                        new
                        {
                            Id = 11,
                            CityId = 3,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 250
                        },
                        new
                        {
                            Id = 12,
                            CityId = 3,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 450
                        },
                        new
                        {
                            Id = 13,
                            CityId = 34,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 500
                        },
                        new
                        {
                            Id = 14,
                            CityId = 34,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 600
                        },
                        new
                        {
                            Id = 15,
                            CityId = 34,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 200
                        },
                        new
                        {
                            Id = 16,
                            CityId = 34,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 300
                        },
                        new
                        {
                            Id = 17,
                            CityId = 35,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 500
                        },
                        new
                        {
                            Id = 18,
                            CityId = 35,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 250
                        },
                        new
                        {
                            Id = 19,
                            CityId = 35,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 300
                        },
                        new
                        {
                            Id = 20,
                            CityId = 35,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 100
                        },
                        new
                        {
                            Id = 21,
                            CityId = 42,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 120
                        },
                        new
                        {
                            Id = 22,
                            CityId = 42,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 250
                        },
                        new
                        {
                            Id = 23,
                            CityId = 42,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 120
                        },
                        new
                        {
                            Id = 24,
                            CityId = 42,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 230
                        },
                        new
                        {
                            Id = 25,
                            CityId = 6,
                            Date = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 350
                        },
                        new
                        {
                            Id = 26,
                            CityId = 6,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 275
                        },
                        new
                        {
                            Id = 27,
                            CityId = 6,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 450
                        },
                        new
                        {
                            Id = 28,
                            CityId = 6,
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VisitorCount = 500
                        });
                });

            modelBuilder.Entity("DataStillCase.Entity.Models.Tables.Information", b =>
                {
                    b.HasOne("DataStillCase.Entity.Models.Tables.City", "City")
                        .WithMany("Informations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DataStillCase.Entity.Models.Tables.VisitorHistory", b =>
                {
                    b.HasOne("DataStillCase.Entity.Models.Tables.City", "City")
                        .WithMany("VisitorHistories")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DataStillCase.Entity.Models.Tables.City", b =>
                {
                    b.Navigation("Informations");

                    b.Navigation("VisitorHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
